
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-5pm-2
owner: ucsb-cs156-s24
repo_name: team02-s24-5pm-2
pull_requests: [{"author":{"id":"U_kgDOBsO-4g","is_bot":false,"login":"richardfang888","name":"Richard Fang"},"headRefName":"Richard-MenuItemReview","number":55,"title":"Richard-MenuItemReview Everything Completed","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-2/pull/55"},{"author":{"id":"U_kgDOBtOfzg","is_bot":false,"login":"abhishekambastha04","name":"Abhi"},"headRefName":"Abhishek-READMELinks","number":51,"title":"Update README.md","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-2/pull/51"},{"author":{"id":"U_kgDOBtOfzg","is_bot":false,"login":"abhishekambastha04","name":"Abhi"},"headRefName":"Abhishek-UCSBDiningCommonsMenuItemsPutMapping","number":48,"title":"Abhishek UCSB Dining Commons Menu Items Put Mapping","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-2/pull/48"},{"author":{"id":"U_kgDOBtOfzg","is_bot":false,"login":"abhishekambastha04","name":"Abhi"},"headRefName":"Abhishek-UCSBDiningCommonsMenuItemsDeleteMapping","number":47,"title":"Abhishek - UCSB Dining Commons Menu Items Delete Mapping","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-2/pull/47"},{"author":{"id":"U_kgDOBtOfzg","is_bot":false,"login":"abhishekambastha04","name":"Abhi"},"headRefName":"Abhishek-UCSBDiningCommonsMenuItemsGetMapping","number":46,"title":"Abhishek UCSB Dining Commons Menu Items Get Mapping","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-2/pull/46"}]
